extends Node

signal on_searched_container
signal on_next_to_searchable(search_var)
signal on_give_item(type,amount)
signal on_closed_container
signal doorway_entered
signal doorway_exited
signal is_opening_inventory
signal close_inventory
signal hide_entire_hud
signal show_entire_hud
