extends Node

# warning-ignore:unused_signal
signal on_searched_container
# warning-ignore:unused_signal
signal on_next_to_searchable(search_var)
# warning-ignore:unused_signal
signal on_give_item(type,amount)
# warning-ignore:unused_signal
signal next_to_this_wall(area)
# warning-ignore:unused_signal
signal on_closed_container
# warning-ignore:unused_signal
signal doorway_entered
# warning-ignore:unused_signal
signal doorway_exited
# warning-ignore:unused_signal
signal is_opening_inventory
# warning-ignore:unused_signal
signal close_inventory
# warning-ignore:unused_signal
signal hide_entire_hud
# warning-ignore:unused_signal
signal show_entire_hud
# warning-ignore:unused_signal
signal pressing_place_fire
# warning-ignore:unused_signal
signal pressing_use_repair
# warning-ignore:unused_signal
signal pressing_place_ice_wall
# warning-ignore:unused_signal
signal build_fire
# warning-ignore:unused_signal
signal build_ice_wall
# warning-ignore:unused_signal
signal use_repair_kit
# warning-ignore:unused_signal
signal no_fire_kit
# warning-ignore:unused_signal
signal no_ice_wall
# warning-ignore:unused_signal
signal no_repair_kit
# warning-ignore:unused_signal
signal not_surrounded_by_ice
# warning-ignore:unused_signal
signal trying_to_build_indoor
# warning-ignore:unused_signal
signal not_next_to_generator
# warning-ignore:unused_signal
signal pressing_use_ice_pick
# warning-ignore:unused_signal
signal ice_pick_not_near_wall
# warning-ignore:unused_signal
signal to_close_to_building
# warning-ignore:unused_signal
signal need_to_move
signal looking_for_ice_wall
